create table ORDERS
(
    id           int generated by default as identity primary key,
    date         timestamp    not null,
    customer_id  int references customers (id),
    product_name varchar(255) not null,
    amount       int          not null

);
insert into ORDERS (date, customer_id, product_name, amount)
values (current_date, 3, 'smartphone', 1);