create table CUSTOMERS
(
    id           int generated by default as identity primary key,
    name         varchar(255) not null,
    surname      varchar(255) not null,
    age          int          not null,
    phone_number varchar(255) not null,
);

insert into CUSTOMERS (NAME, SURNAME, AGE, PHONE_NUMBER)
values ('IVAN', 'IVANOV', 30, +79990000000);
    ('PETER', 'PETROV', 35, +79980000000);
    ('ALEXEY', 'ALEXANDROV', 40, +79970000000);